import type { Metadata } from "next";
import { Bricolage_Grotesque, DM_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";

const dmSans = DM_Sans({
  variable: "--font-dm",
  weight: ["300", "500", "600", "700"],
  style: ["italic", "normal"],
});

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bg",
  weight: "700",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${bricolageGrotesque.variable}`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
